"""
PDF season report generation, via reportlab (pure-Python, no system
dependencies — chosen over WeasyPrint specifically for portability, since
WeasyPrint needs Pango/Cairo system libraries that complicate a "clone and
run" experience, especially on Windows where this project's `py main.py`
entry point suggests at least some users will be).
"""
from __future__ import annotations

import io

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from config.constants import SEASON
from engine.monte_carlo import simulate_season


def season_report_pdf(n_sims: int = 300) -> bytes:
    """Generates a short PDF: title page + projected table. Returns raw PDF bytes,
    ready to send via Flask's send_file / Response(mimetype='application/pdf')."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph(f"EPL Predictor — {SEASON} Season Report", styles["Title"]))
    story.append(Paragraph(
        f"Monte Carlo projection ({n_sims} simulated seasons). Illustrative model inputs — "
        "not licensed provider data. Generated by reports/pdf_generator.py.",
        styles["Normal"],
    ))
    story.append(Spacer(1, 1 * cm))

    projection = simulate_season(n_sims=n_sims, seed="pdf-report")
    table_data = [["#", "Club", "Pts", "Title %", "Top 4 %", "Releg %"]]
    for i, r in enumerate(projection, start=1):
        table_data.append([
            str(i), r.club_id.upper(), f"{r.avg_points:.0f}",
            f"{r.title_prob*100:.1f}", f"{r.top4_prob*100:.1f}", f"{r.releg_prob*100:.1f}",
        ])

    table = Table(table_data, colWidths=[1.2 * cm, 4 * cm, 2 * cm, 2.5 * cm, 2.5 * cm, 2.5 * cm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1B0E2E")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#DDDDDD")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F5F2F8")]),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(table)

    doc.build(story)
    return buf.getvalue()
